# Generated by Django 5.0.6 on 2024-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField()),
                ('Course', models.CharField(choices=[('Full Stack Java', 'Full Stack Java'), ('Full Stack Python', 'Full Stack Python'), ('Data Science', 'Data Science'), ('AWS', 'AWS'), ('MERN Stack', 'MERN Stack'), ('Spoken English', 'Spoken English'), ('Data Analytics', 'Data Analytics'), ('DevOps', 'DevOps')], default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
